<?php

namespace DesignByCode\Admin\Http\Controllers\DataTables;

use App\Http\Controllers\Controller;
use DesignByCode\Admin\Http\Requests\UpdateCategoriesRequest;
use DesignByCode\Admin\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends DataTableController
{
    protected $allowCreation = false;
    protected $searchable = true;
    protected $allowDeletion = true;
    protected $modalText = 'Category';

    /**
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function builder() {
        return Category::query();
    }

    /**
     * @return array
     */
    public function getDisplayableColumns()
    {
        return ['id','name', 'slug'];
    }
    /**
     * @return array
     */
    public function getUpdatableColumns()
    {
        return ['name'];
    }

    /**
     * @param $id
     * @param Request $request
     */
    public function update($id, Request $request)
    {
        $request->validate([
            'name' => 'required|unique:categories,name,' . $id
        ]);
        parent::update($id, $request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     */
    public function store(Request $request)
    {
        $request->validate([
           'name' => 'required|unique:categories,name,' . $request->id
        ]);
        return parent::store($request); // TODO: Change the autogenerated stub
    }

}
