<?php

namespace DesignByCode\Admin\Http\Controllers\DataTables;

use App\Http\Controllers\Controller;
use DesignByCode\Tagger\Models\Tag;
use Illuminate\Http\Request;

class TagsController extends DataTableController
{

    protected $allowDeletion = true;
    protected $searchable = true;
    protected $allowFullEdit = false;


    public function builder()
    {
        return Tag::query();
    }

    public function getDisplayableColumns()
    {
        return ['id', 'name', 'slug'];
    }

    public function getUpdatableColumns()
    {
        return ['name'];
    }

    /**
     * @param $id
     * @param Request $request
     */
    public function update($id, Request $request)
    {
        $request->validate([
            'name' => 'required|unique:tags,name,' . $id
        ]);

        parent::update($id, $request); // TODO: Change the autogenerated stub
    }


}
